apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: dice-job-container
        image: kodekloud/throw-dice
      restartPolicy: Never
  backoffLimit: 90
  completions: 5
  parallelism: 3
