apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-vol
  labels:
    name: per-vol
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity: 
    storage:  100Mi
  hostPath: 
    path: /mnt/data
  
