apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo "This is the practice of empty dir volume" > cat /data/new.txt']
    volumeMounts:
    - name: emptydir
      mountPath: /data

  volumes:
  - name: emptydir
    emptyDir: {}
      
