apiVersion: v1
kind: Service
metadata:
  name: db-dev-service
  namespace: new-namespace
spec:
  type: NodePort
  selector:
    name: blue
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

