apiVersion: v1
kind: Pod
metadata:
  name: db-dev-pod
  namespace: new-namespace
  labels:
    name: blue
spec:
  containers:
  - name:  redis
    image: redis:alpine
    env:
    - name: REDIS_ROOT_PASSWORD
      value: paswr 
    ports:
    - containerPort: 6379
      protocol: TCP

